### ISSUE TITLE
Allow an environment variable to provide extra search-paths to `mcstas-antlr` and `mcxtrace-antlr`

### ISSUE THREAD

**Issue by g5t** [mccode-dev/mccode-antlr#136]
Systems with McStas and/or McXtrace installed from conda-forge have environment variable(s) `$MCSTAS` and/or `$MCXTRACE` pointing to 'resource' directories which _should_ be equivalent to the same-version tag remote repository registries.
On such a system, downloading component files a second time is unnecessary and duplicative. This can be overcome by specifying a 'search-dir' when calling `mcstas-antlr` or `mcxtrace-antlr`, e.g.
```cmd
~$ mcstas-antlr -I "${MCSTAS}" ...
~$ mcxtrace-antlr --search-dir "${MCXTRACE}" ...
```

Directly using either environment variable could be problematic, and would force a user to override a McStas/McXtrace setting to _not_ use distributed component(s) with `mcstas-antlr`/`mcxtrace-antlr`.

Instead, the standard `confuse` interface for reading environment variables can be used, and a user (or system administrator) can make the appropriate definition.

Currently the `confuse` `default_config.yml` file contains
```yml
mcstas:
  name: mcstas
  particle: neutron
  particle_code: 2112
  lib: nlib
  libenv: MCSTAS
  prefix: mc
  project: 1
mcxtrace:
  name: mcxtrace
  particle: xray
  particle_code: 22
  lib: xlib
  libenv: MCXTRACE
  prefix: mx
  project: 2
mccode_pooch:
  source: https://github.com/mccode-dev/McCode
  registry: https://github.com/mccode-dev/mccode-pooch-registries
  tag: latest
```
and a key like `mcstas.prefix` would be overridden by the environment variable `MCCODEANTLR_MCSTAS_PREFIX="mcc"`.

Extra configuration entries can be searched for, including via environment variable population, so specifying, e.g., 
```cmd
~$ export MCCODEANTLR_MCSTAS_PATHS="${MCSTAS}"
```
would allow for later code like
```python
local_search_paths = []
if 'paths' in config['mcstas']:
    for path_str in config['mcstas']['paths'].as_str_seq():
        local_search_paths.append(Path(path_str))
```
